#!/usr/bin/env bash
set -euo pipefail

if ! command -v tsp >/dev/null 2>&1; then
  echo "Errore: 'tsp' non trovato. Installa task-spooler (ts/tsp)."
  exit 1
fi

if [[ ! -x ./venv/bin/python ]]; then
  echo "Errore: interprete Python non trovato in ./venv/bin/python"
  exit 1
fi

echo "Accodamento combinazioni esplicite..."
echo "Queue -> dataset=owt model=gemma2_9b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=owt model=gemma2_9b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=bert machine_postfix=h2l
echo "Queue -> dataset=owt model=gemma2_9b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=owt model=gemma2_9b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=owt model=gemma2_9b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=owt model=gemma2_9b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=owt model=gemma2_9b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=owt model=gemma2_9b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=owt model=gemma2_9b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=owt model=gemma2_9b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=owt model=gemma2_9b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=radar machine_postfix=h2l
echo "Queue -> dataset=owt model=gemma2_9b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=owt model=gemma2_9b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=owt model=gemma2_9b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=owt model=gemma2_9b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=gemma2_9b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=owt model=llama32_2b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=owt model=llama32_2b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=bert machine_postfix=h2l
echo "Queue -> dataset=owt model=llama32_2b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=owt model=llama32_2b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=owt model=llama32_2b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=owt model=llama32_2b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=owt model=llama32_2b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=owt model=llama32_2b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=owt model=llama32_2b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=owt model=llama32_2b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=owt model=llama32_2b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=radar machine_postfix=h2l
echo "Queue -> dataset=owt model=llama32_2b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=owt model=llama32_2b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=owt model=llama32_2b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=owt model=llama32_2b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=llama32_2b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=owt model=mistral7b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=owt model=mistral7b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=bert machine_postfix=h2l
echo "Queue -> dataset=owt model=mistral7b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=owt model=mistral7b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=owt model=mistral7b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=owt model=mistral7b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=owt model=mistral7b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=owt model=mistral7b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=owt model=mistral7b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=owt model=mistral7b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=owt model=mistral7b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=radar machine_postfix=h2l
echo "Queue -> dataset=owt model=mistral7b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=owt model=mistral7b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=owt model=mistral7b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=owt model=mistral7b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=mistral7b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=owt model=qwen25_7b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=owt model=qwen25_7b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=bert machine_postfix=h2l
echo "Queue -> dataset=owt model=qwen25_7b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=owt model=qwen25_7b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=owt model=qwen25_7b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=owt model=qwen25_7b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=owt model=qwen25_7b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=owt model=qwen25_7b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=owt model=qwen25_7b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=owt model=qwen25_7b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=owt model=qwen25_7b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=radar machine_postfix=h2l
echo "Queue -> dataset=owt model=qwen25_7b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=owt model=qwen25_7b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=owt model=qwen25_7b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=owt model=qwen25_7b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=owt model=qwen25_7b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=wp model=gemma2_9b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=wp model=gemma2_9b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=bert machine_postfix=h2l
echo "Queue -> dataset=wp model=gemma2_9b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=wp model=gemma2_9b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=wp model=gemma2_9b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=wp model=gemma2_9b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=wp model=gemma2_9b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=wp model=gemma2_9b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=wp model=gemma2_9b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=wp model=gemma2_9b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=wp model=gemma2_9b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=radar machine_postfix=h2l
echo "Queue -> dataset=wp model=gemma2_9b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=wp model=gemma2_9b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=wp model=gemma2_9b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=wp model=gemma2_9b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=gemma2_9b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=wp model=llama32_2b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=wp model=llama32_2b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=bert machine_postfix=h2l
echo "Queue -> dataset=wp model=llama32_2b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=wp model=llama32_2b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=wp model=llama32_2b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=wp model=llama32_2b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=wp model=llama32_2b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=wp model=llama32_2b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=wp model=llama32_2b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=wp model=llama32_2b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=wp model=llama32_2b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=radar machine_postfix=h2l
echo "Queue -> dataset=wp model=llama32_2b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=wp model=llama32_2b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=wp model=llama32_2b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=wp model=llama32_2b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=llama32_2b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=wp model=mistral7b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=wp model=mistral7b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=bert machine_postfix=h2l
echo "Queue -> dataset=wp model=mistral7b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=wp model=mistral7b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=wp model=mistral7b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=wp model=mistral7b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=wp model=mistral7b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=wp model=mistral7b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=wp model=mistral7b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=wp model=mistral7b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=wp model=mistral7b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=radar machine_postfix=h2l
echo "Queue -> dataset=wp model=mistral7b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=wp model=mistral7b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=wp model=mistral7b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=wp model=mistral7b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=mistral7b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=wp model=qwen25_7b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=wp model=qwen25_7b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=bert machine_postfix=h2l
echo "Queue -> dataset=wp model=qwen25_7b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=wp model=qwen25_7b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=wp model=qwen25_7b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=wp model=qwen25_7b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=wp model=qwen25_7b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=wp model=qwen25_7b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=wp model=qwen25_7b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=wp model=qwen25_7b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=wp model=qwen25_7b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=radar machine_postfix=h2l
echo "Queue -> dataset=wp model=qwen25_7b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=wp model=qwen25_7b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=wp model=qwen25_7b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=wp model=qwen25_7b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=wp model=qwen25_7b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=xsum model=gemma2_9b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=bert machine_postfix=h2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=xsum model=gemma2_9b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=xsum model=gemma2_9b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=xsum model=gemma2_9b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=radar machine_postfix=h2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=xsum model=gemma2_9b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=xsum model=gemma2_9b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=gemma2_9b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=xsum model=llama32_2b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=xsum model=llama32_2b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=bert machine_postfix=h2l
echo "Queue -> dataset=xsum model=llama32_2b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=xsum model=llama32_2b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=xsum model=llama32_2b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=xsum model=llama32_2b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=xsum model=llama32_2b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=xsum model=llama32_2b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=xsum model=llama32_2b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=xsum model=llama32_2b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=xsum model=llama32_2b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=radar machine_postfix=h2l
echo "Queue -> dataset=xsum model=llama32_2b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=xsum model=llama32_2b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=xsum model=llama32_2b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=xsum model=llama32_2b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=llama32_2b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=xsum model=mistral7b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=xsum model=mistral7b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=bert machine_postfix=h2l
echo "Queue -> dataset=xsum model=mistral7b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=xsum model=mistral7b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=xsum model=mistral7b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=xsum model=mistral7b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=xsum model=mistral7b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=xsum model=mistral7b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=xsum model=mistral7b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=xsum model=mistral7b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=xsum model=mistral7b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=radar machine_postfix=h2l
echo "Queue -> dataset=xsum model=mistral7b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=xsum model=mistral7b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=xsum model=mistral7b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=xsum model=mistral7b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=mistral7b detector=roberta machine_postfix=llm2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=bert machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=bert machine_postfix=free_llm
echo "Queue -> dataset=xsum model=qwen25_7b detector=bert machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=bert machine_postfix=h2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=bert machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=bert machine_postfix=llm2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=binoculars machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=binoculars machine_postfix=free_llm
echo "Queue -> dataset=xsum model=qwen25_7b detector=binoculars machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=binoculars machine_postfix=h2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=binoculars machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=binoculars machine_postfix=llm2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=fastdetectgpt machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=fastdetectgpt machine_postfix=free_llm
echo "Queue -> dataset=xsum model=qwen25_7b detector=fastdetectgpt machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=fastdetectgpt machine_postfix=h2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=fastdetectgpt machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=fastdetectgpt machine_postfix=llm2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=radar machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=radar machine_postfix=free_llm
echo "Queue -> dataset=xsum model=qwen25_7b detector=radar machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=radar machine_postfix=h2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=radar machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=radar machine_postfix=llm2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=roberta machine_postfix=free_llm"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=roberta machine_postfix=free_llm
echo "Queue -> dataset=xsum model=qwen25_7b detector=roberta machine_postfix=h2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=roberta machine_postfix=h2l
echo "Queue -> dataset=xsum model=qwen25_7b detector=roberta machine_postfix=llm2l"
tsp ./venv/bin/python run_detector.py dataset=xsum model=qwen25_7b detector=roberta machine_postfix=llm2l

echo "Tutte le combinazioni sono state accodate con tsp."
